name: 'depcache'
description: 'cache dependencies'
author: 'qawatake'

inputs:
  dependency-path:
    description: 'Used to specify the path to a dependency file'
    required: true
  path:
    description: 'Used to specify the path to the cache'
    required: true
  skip-save:
    description: 'Used to specify whether to skip saving the cache'
    required: true
  github-token:
    description: 'Used to fetch workflow info'
    required: true

outputs:
  cache-hit:
    description: 'Whether the cache was hit or not'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
  post-if: '!github.event.inputs.skip-save'
