name: 'depcache'
description: 'cache dependencies'
author: 'qawatake'

inputs:
  dependency-path:
    description: 'Used to specify the path to a dependency file'
    required: true
  path:
    description: 'Used to specify the path to the cache'
    required: true
  skip-save:
    description: 'Used to specify whether to skip saving the cache'
    required: true
  github-token:
    description: 'Used to delete cache'
    required: true

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
  post-if: '!github.event.inputs.skip-save'
